version: "3.7"

services:
  app:
    build: .
    restart: always
    ports:
      - 4000:80
    volumes:
      - ./pages:/home/pages
      - ./images:/home/images
    environment: 
      - VERSION=$TAG