name: "Deploy"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build . --tag thalkz.com --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log into ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - uses: olegtarasov/get-tag@v2.1.2

      - name: Push image
        run: |
          docker tag thalkz.com ghcr.io/thalkz/thalkz.com:$GIT_TAG_NAME
          docker tag thalkz.com ghcr.io/thalkz/thalkz.com:latest
          docker push --all-tags ghcr.io/thalkz/thalkz.com

      - name: Deploy to host
        uses: appleboy/ssh-action@master
        with:
          host: thalkz.com
          username: ubuntu
          key: ${{ secrets.HELLION_SSH_KEY }}
          script: |
            cd ./thalkz.com
            ./update.sh $GIT_TAG_NAME
